import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./layout.module.scss";
import "./globals.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html> 
        <head> 
            <meta charSet="utf-8" /> 
            <meta name="viewport" content="width=device-width, initial-scale=1" /> 
            <meta name="theme-color" content="#000000" /> 
        </head> 
        <body className={`${inter.className} ${styles.container}`}>{children}</body>
    </html>
  );
}
